loadFramePacks([
	{name:'Regular', value:'TokenRegular-1'},
	{name:'Textless', value:'TokenTextless-1'},
	{name:'Textless (Borderless)', value:'TokenTextlessBorderless'},
	{name:'Tall', value:'TokenTall-1'},
	{name:'Short', value:'TokenShort-1'},
	{name:'Monarch Token', value:'TokenMonarch'},
	{name:'Initiative Token', value:'TokenInitiative'},
	{name:'Day/Night Marker', value:'TokenDayNight'},
	{name:'Planeswalker Emblems', value:'Emblem'},
	{name:'Jumpstart Front Cards', value:'JMPFront'},
	{name:'Jumpstart 2022 Front Cards', value:'J22Front'},
	{name:'Older Tokens', value:'disabled'},
	{name:'Regular (Bordered M15)', value:'TokenRegularM15'},
	{name:'Textless (Bordered M15)', value:'TokenTextlessM15'},
	{name:'Original (Old Bordered)', value:'TokenOld'},
	{name:'Unglued', value:'TokenUnglued'},
	{name:'Addons', value:'disabled'},
	{name:'Floating Legend Crowns', value:'M15LegendCrownsFloating'},
	{name:'Inner Crowns', value:'M15InnerCrowns'},
	{name:'Holo Stamps', value:'M15HoloStamps'},
	{name:'Dark Power/Toughness', value:'M15DarkPT'},
	{name:'Colored Borders', value:'M15Borders'},
	{name:'"The List" Stamp', value:'TheList'},
	{name:'Custom Addons', value:'disabled'},
	{name:'Brawl Legend Crowns', value:'Brawl'}
])