loadFramePacks([
	{name:'Eternal Night (MID)', value:'EternalNight'},
	{name:'D&D Sourcebook', value:'DNDSourcebook'},
	{name:'D&D Module', value:'DNDModule'},
	{name:'Sketch Cards (MH2)', value:'MH2'},
	{name:'Mystical Archive', value:'MysticalArchive'},
	{name:'Mystical Archive (Japanese)', value:'MysticalArchiveJP'},
	{name:'Mystical Archive (Japanese, Horizontal)', value:'MysticalArchiveJPHorizontal'},
	{name:'Praetors', value:'Praetors'},
	{name:'Kaldheim', value:'Kaldheim-2'},
	{name:'Kaldheim (Nonlegendary)', value:'KaldheimNonleg'},
	{name:'Commander Legends', value:'CommanderLegends'},
	{name:'Zendikar Rising', value:'ZendikarRising'},
	{name:'M21', value:'M21'},
	{name:'Theros Beyond Death', value:'M15NyxShowcase'},
	{name:'Eldraine Storybooks', value:'Storybook'},
	{name:'Generic Showcase', value:'GenericShowcase'},
	{name:'Masterpieces/Other', value:'disabled'},
	{name:'Nickname', value:'M15Nickname'},
	{name:'Extended Art (Regular)', value:'M15BoxTopper'},
	{name:'Extended Art (Shorter Textbox)', value:'M15ExtendedArtShort'},
	{name:'ZNR Expeditions (2020)', value:'ExpeditionZNR-1'},
	{name:'Signature Spellbook (Jace/Gideon)', value:'SignatureSpellbook'},
	{name:'Ixalan Maps', value:'Ixalan'},
	{name:'Amonkhet Invocations (u/Smyris)', value:'Invocation'},
	{name:'Kaladesh Inventions', value:'Invention'},
	{name:'BFZ Expeditions (2015)', value:'ExpeditionBFZ-1'},
	{name:'SDCC15 (Blackout)', value:'SDCC15'},
	{name:'Addons', value:'disabled'},
	{name:'Legend Crowns', value:'M15LegendCrowns'},
	{name:'Floating Legend Crowns', value:'M15LegendCrownsFloating'},
	{name:'Inner Crowns', value:'M15InnerCrowns'},
	{name:'Holo Stamps', value:'M15HoloStamps'},
	{name:'Dark Power/Toughness', value:'M15DarkPT'},
	{name:'Colored Borders', value:'M15Borders'},
	{name:'Color Identity Pips', value:'M15CIPips'},
	{name:'"The List" Stamp', value:'TheList'}
])