loadFramePacks([
	{name:'Set Showcase Frames (Chronological)', value:'disabled'},
	{name:'Breaking News (OTP)', value:'BreakingNews'},
	{name:'Vault (BIG)', value:'Vault'},
	{name:'Wanted Poster (OTJ)', value:'Wanted'},
	{name:'Pip-Boy (PIP)', value:'Pipboy'},
	{name:'Dossier (MKM)', value:'Dossier'},
	{name:'Scrolls of Middle-earth (LTR)', value:'Scroll'},
	{name:'Enchanting Tales (WOT)', value:'EnchantingTales'},
	{name:'Eldraine Storybooks: Adventures (WOE)', value:'StorybookWOE'},
	{name:'TARDIS (WHO)', value:'TARDIS'},
	{name:'Ring (LTR)', value:'Ring'},
	{name:'Eldraine Storybooks (MOM)', value:'StorybookMUL'},
	{name:'Ixalan Coin (MOM)', value:'IxalanCoin'},
	{name:'Tarkir Sketch (MOM)', value:'Tarkir'},
	{name:'Ikoria Crystal (MOM)', value:'Crystal'},
	{name:'Ravnica City (MOM)', value:'Ravnica'},
	{name:'Oil Slick (ONE)', value:'OilSlick'},
	{name:'Stained Glass (DMU)', value:'DMUStainedGlass'},
	{name:'Golden Age (SNC)', value:'SNCGilded'},
	{name:'Art Deco (SNC)', value:'SNCArtDeco'},
	{name:'Skyscraper (SNC)', value:'SNCSkyscraper'},
	{name:'Ninja (NEO)', value:'NeoNinja'},
	{name:'Samurai (NEO)', value:'NeoSamurai'},
	{name:'Neon (NEO)', value:'NeoNeon'},
	{name:'Double Feature (DBL)', value:'DoubleFeature'},
	{name:'Double Feature: Transform (DBL)', value:'DoubleFeatureTransform'},
	{name:'Fang (VOW)', value:'Fang'},
	{name:'Equinox: Single-faced (MID)', value:'Equinox'},
	{name:'Equinox: Transform Front (MID)', value:'EquinoxFront'},
	{name:'Equinox: Transform Back (MID)', value:'EquinoxBack'},
	{name:'Eternal Night (MID)', value:'EternalNight'},
	{name:'D&D Sourcebook (AFR)', value:'DNDSourcebook'},
	{name:'D&D Module (AFR)', value:'DNDModule'},
	{name:'Sketch Cards (MH2)', value:'MH2'},
	{name:'Mystical Archive (STA)', value:'MysticalArchive'},
	{name:'Japanese Mystical Archive (STA)', value:'MysticalArchiveJP'},
	{name:'Horizontal Japanese Mystical Archive (STA)', value:'MysticalArchiveJPHorizontal'},
	{name:'Kaldheim (KHM)', value:'Kaldheim-2'},
	{name:'Nonlegendary Kaldheim (KHM)', value:'KaldheimNonleg'},
	{name:'Commander Legends (CMR)', value:'CommanderLegends'},
	{name:'Zendikar Rising (ZNR)', value:'ZendikarRising'},
	{name:'M21 Signature Spellbooks (M21)', value:'M21'},
	{name:'Theros Beyond Death (THB)', value:'M15NyxShowcase'},
	{name:'Eldraine Storybooks: Adventures (ELD)', value:'Storybook'},

	{name:'Generic Showcase Frames', value:'disabled'},
	{name:'Borderless', value:'GenericShowcase'},
	{name:'Borderless (Alt)', value:'Borderless'},
	{name:'Fullart', value:'M15ClearTextboxes'},
	{name:'Nickname ("Godzilla")', value:'M15Nickname'},
	{name:'Extended Art (Regular)', value:'M15BoxTopper'},
	{name:'Extended Art (Shorter Textbox)', value:'M15ExtendedArtShort'},
	{name:'FNM Promo (Inverted Promos)', value:'FNM'},
	{name:'Full Text', value:'FullText'},
	{name:'Full Text (Alt)', value:'FullTextAlt'},
	{name:'Foil-Etched', value:'disabled'},
	{name:'Etched', value:'Etched'},
	{name:'Etched (Nyx)', value:'EtchedNyx'},
	{name:'Etched (Snow)', value:'EtchedSnow'},
	{name:'Legend Crowns (Etched)', value:'LegendCrownsEtched'},
	{name:'Inner Crowns (Etched)', value:'InnerCrownsEtched'},
	
	{name:'Universes Beyond', value:'disabled'},
	{name:'Universes Beyond', value:'UB'},
	{name:'Universes Beyond (Full art)', value:'UBFull'},
	{name:'Universes Beyond (Extended art)', value:'UBExtendedArt'},
	{name:'Legend Crowns (Universes Beyond)', value:'UBLegendCrowns'},
	{name:'Floating Legend Crowns (Universes Beyond)', value:'UBLegendCrownsFloating'},
	
	{name:'Masterpieces/Other', value:'disabled'},
	{name:'Phyrexian', value:'Praetors'},
	{name:'ZNR Expeditions (2020)', value:'ExpeditionZNR-1'},
	{name:'Signature Spellbook (Jace/Gideon)', value:'SignatureSpellbook'},
	{name:'Ixalan Maps', value:'Ixalan'},
	{name:'Amonkhet Invocations (u/Smyris)', value:'Invocation'},
	{name:'Amonkhet Invocations (Multiverse Legends)', value:'InvocationMUL'},
	{name:'Kaladesh Inventions', value:'Invention'},
	{name:'BFZ Expeditions (2015)', value:'ExpeditionBFZ-1'},
	{name:'SDCC15 (Blackout)', value:'SDCC15'},
	{name:'Future Shifted', value:'FutureRegular'},

	{name:'Addons', value:'disabled'},
	{name:'Legend Crowns', value:'M15LegendCrowns'},
	{name:'Legend Crowns (Universes Beyond)', value:'UBLegendCrowns'},
	{name:'Floating Legend Crowns', value:'M15LegendCrownsFloating'},
	{name:'Floating Legend Crowns (Universes Beyond)', value:'UBLegendCrownsFloating'},
	{name:'Inner Crowns', value:'M15InnerCrowns'},
	{name:'Nicknames', value:'M15Nickname-2'},
	{name:'Holo Stamps', value:'M15HoloStamps'},
	{name:'Dark Power/Toughness', value:'M15DarkPT'},
	{name:'Colored Borders', value:'M15Borders'},
	{name:'Color Identity Pips', value:'M15CIPips'},
	{name:'"The List" Stamp', value:'TheList'},

	{name:'Custom Addons', value:'disabled'},
	{name:'Brawl Legend Crowns', value:'Brawl'}
])