loadFramePacks([
	{name:'Regular Frames', value:'M15Regular-1'},
	{name:'Addons', value:'disabled'},
	{name:'Legend Crowns', value:'M15LegendCrowns'},
	{name:'Floating Legend Crowns', value:'M15LegendCrownsFloating'},
	{name:'Inner Crowns', value:'M15InnerCrowns'},
	{name:'Nicknames', value:'M15Nickname-2'},
	{name:'Miracle', value:'M15Miracle'},
	{name:'Holo Stamps', value:'M15HoloStamps'},
	{name:'Dark Power/Toughness', value:'M15DarkPT'},
	{name:'Colored Borders', value:'M15Borders'},
	{name:'Color Identity Pips', value:'M15CIPips'},
	{name:'"The List" Stamp', value:'TheList'},
	{name:'Other Frames', value:'disabled'},
	{name:'Lands', value:'M15Lands'},
	{name:'Spree (Outlaws of Thunder Junction)', value:'Spree'},
	{name:'Cases (Murders at Karlov Manor)', value:'Case'},
	{name:'Battle (March of the Machine)', value:'Battle'},
	{name:'Prototype (Brothers\' War)', value:'Prototype'},
	{name:'Prototype (Extended Art) (Brothers\' War)', value:'PrototypeExtended'},
	{name:'Attractions (Unfinity)', value:'Attraction'},
	{name:'Class (D&D)', value:'Class'},
	{name:'Snow (Kaldheim)', value:'M15Snow'},
	{name:'Mutate (Ikoria)', value:'M15Mutate'},
	{name:'Nyx (Theros)', value:'M15Nyx'},
	{name:'Adventures (Eldraine)', value:'Adventure'},
	{name:'Devoid (Zendikar)', value:'M15Devoid'},
	{name:'Aftermath (Amonkhet)', value:'Aftermath'},
	{name:'Flip (Kamigawa)', value:'Flip'},
	{name:'Levelers (Zendikar)', value:'Levelers'},
	{name:'Split Cards', value:'Split'},
	{name:'Fuse Cards', value:'Fuse'},
	{name:'Conspiracies (Draft Matters)', value:'Conspiracy'},
	{name:'Colorshifted (Planar Chaos)', value:'Colorshifted'},
	{name:'Custom Addons', value:'disabled'},
	{name:'Brawl Legend Crowns', value:'Brawl'}
])