loadFramePacks([
	{name:'Regular Frames', value:'M15Regular-1'},
	{name:'Addons', value:'disabled'},
	{name:'Legend Crowns', value:'M15LegendCrowns'},
	{name:'Floating Legend Crowns', value:'M15LegendCrownsFloating'},
	{name:'Inner Crowns', value:'M15InnerCrowns'},
	{name:'Holo Stamps', value:'M15HoloStamps'},
	{name:'Dark Power/Toughness', value:'M15DarkPT'},
	{name:'Colored Borders', value:'M15Borders'},
	{name:'Other Frames', value:'disabled'},
	{name:'Lands', value:'M15Lands'},
	{name:'Snow', value:'M15Snow'},
	{name:'Nyx', value:'M15Nyx'},
	{name:'Devoid', value:'M15Devoid'},
	{name:'Special', value:'disabled'},
	{name:'Nickname', value:'M15Nickname'},
	{name:'Extended Art (Box Topper)', value:'M15BoxTopper'},
	{name:'Custom Addons', value:'disabled'},
	{name:'Brawl Legend Crowns', value:'Brawl'}
])