loadFramePacks([
	{name:'Mystical Archive', value:'MysticalArchive'},
	{name:'Praetors', value:'Praetors'},
	{name:'Kaldheim', value:'Kaldheim-2'},
	{name:'Kaldheim (Nonlegendary)', value:'KaldheimNonleg'},
	{name:'Commander Legends', value:'CommanderLegends'},
	{name:'Zendikar Rising', value:'ZendikarRising'},
	{name:'M21', value:'M21'},
	{name:'Theros Beyond Death', value:'M15NyxShowcase'},
	{name:'Eldraine Storybooks', value:'Storybook'},
	{name:'Generic Showcase', value:'GenericShowcase'},
	{name:'Masterpieces/Other', value:'disabled'},
	{name:'Nickname', value:'M15Nickname'},
	{name:'Box Toppers', value:'M15BoxTopper'},
	{name:'ZNR Expeditions (2020)', value:'ExpeditionZNR-1'},
	{name:'Ixalan Maps', value:'Ixalan'},
	{name:'Kaladesh Inventions', value:'Invention'},
	{name:'BFZ Expeditions (2015)', value:'ExpeditionBFZ-1'},
	{name:'Addons', value:'disabled'},
	{name:'Legend Crowns', value:'M15LegendCrowns'},
	{name:'Floating Legend Crowns', value:'M15LegendCrownsFloating'},
	{name:'Inner Crowns', value:'M15InnerCrowns'},
	{name:'Holo Stamps', value:'M15HoloStamps'},
	{name:'Dark Power/Toughness', value:'M15DarkPT'},
	{name:'Colored Borders', value:'M15Borders'},
	{name:'Custom Addons', value:'disabled'},
	{name:'Brawl Legend Crowns', value:'Brawl'}
])